### ISSUE TITLE
when i run go run main.go

### ISSUE THREAD

**Issue by balook** [mzfr/takeover#9]
main.go:17:2: cannot find package "github.com/parnurzeal/gorequest" in any of:
        /usr/local/bin/go/src/github.com/parnurzeal/gorequest (from $GOROOT)
        /home/balu/go/src/github.com/parnurzeal/gorequest (from $GOPATH)
        
when i run go run main.go

**Comment by mzfr** [comment]
You haven't installed the required go package that is why it gave that error.

Make sure to install all the required packages

**Comment by balook** [comment]
then give go.mod and go.sum to auto download package when running
